language: node_js
node_js:
  - "8.12"
sudo: false
cache:
  yarn: true
  directories:
    - .jest
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH

jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
